version: '3'
services:
  postgresdb:
    build:
      context: ./DB
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./DB/db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "Transaction"]
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 30

  migrate_dev:
    image: migrate/migrate
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
        - ./DB/migrations:/migrations
    command: ["-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/TransactionDev?sslmode=disable", "-path", "/migrations", "up"]

  migrate_test:
    image: migrate/migrate
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
        - ./DB/migrations:/migrations
    command: ["-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/TransactionTest?sslmode=disable", "-path", "/migrations", "up"]

  migrate_prod:
    image: migrate/migrate
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
        - ./DB/migrations:/migrations
    command: ["-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/Transaction?sslmode=disable", "-path", "/migrations", "up"]

  # apiserver:
  #   build:
  #     context: ./MarketPlace
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/usr/src/app
  #   depends_on:
  #     - migrate_prod
  #   ports:
  #     - "8080:8080"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    # depends_on:
      # - apiserver
    ports:
      - "80:80"

volumes:
  db_data: