bind_addr = ":8080"
log_level = "debug"
# database_url = "host=localhost port=5435 user=admin password=qaz dbname=Transaction sslmode=disable"
# rabbit = "amqp://guest:guest@localhost:5672/"
database_url = "host=postgresdb port=5432 user=admin password=qaz dbname=Transaction sslmode=disable"
rabbit = "amqp://guest:guest@rabbitmq:5672/"
session_key = "wnNdfAdoYs6IB1qG0qRFQoxvqWvMSZql"